#!/usr/bin/env python
# coding: utf-8

# In[2]:

#Write a function that computes the volume of a sphere given its radius

def vol(rad):
    return (4/3)*(3.14)*(rad**3)

#Check

vol(2)


# In[5]:


#Write a function that checks whether a number is in a given range (inclusive of high and low)

def ran_check(num,low,high):
    if low<num<high:
        print('{} is in the range between {} and {}'.format(num,low,high))
    else:
        print('The number is outside the range.')

# Check

ran_check(5,2,7)


# In[6]:


#Write a Python function that accepts a string and calculates the number of upper case letters and lower case letters.

def up_low(s):
    d={"upper":0, "lower":0}
    for c in s:
        if c.isupper():
            d["upper"]+=1
        elif c.islower():
            d["lower"]+=1
        else:
            pass
    print("Original String : ", s)
    print("No. of Upper case characters : ", d["upper"])
    print("No. of Lower case Characters : ", d["lower"])
    
#Checks
    
s = 'Hello Mr. Rogers, how are you this fine Tuesday?'
up_low(s)


# In[9]:


#Write a Python function that takes a list and returns a new list with unique elements of the first list.
def unique_list(lst): 
    new_list=[]
    for number in lst:
        if number not in new_list:
            new_list.append(number)
    return new_list

#Checks

unique_list([1,1,1,1,2,2,3,3,3,3,4,5])


# In[11]:


#Write a Python function to multiply all the numbers in a list.

def multiply(numbers):  
    multiply_num = 1
    for number in numbers:
        multiply_num *= number
    return multiply_num

#Checks

multiply([1,2,3,-4])


# In[15]:


#Write a Python function that checks whether a word or phrase is palindrome or not.
#A palindrome is word, phrase, or sequence that reads the same backward as forward, e.g., madam,kayak,racecar, or a phrase "nurses run".

def palindrome(s):
    s = s.replace(' ','') # This replaces all spaces ' ' with no space ''. (Fixes issues with strings that have spaces)
    return s == s[::-1]   # Check through slicing

#Checks

palindrome('helleh')


# In[ ]:




